# Generated by Django 3.1.2 on 2020-10-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[[1, 'Администратор'], [2, 'Сотрудник'], [1, 'Руководитьель']], default=1, verbose_name='Роль пользователя')),
            ],
        ),
    ]
