# Generated by Django 3.1.2 on 2020-10-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[[1, 'Администратор'], [2, 'Сотрудник'], [3, 'Руководитьель']], default=1, verbose_name='Роль пользователя'),
        ),
    ]
