# Generated by Django 3.1.2 on 2020-11-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201031_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
