# Generated by Django 3.1.2 on 2020-11-01 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201101_0058'),
        ('users', '0003_auto_20201101_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.municipality', verbose_name='Муниципалитет'),
        ),
    ]
