# Generated by Django 3.1.2 on 2020-11-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[[1, 'Администратор'], [2, 'Оператор'], [3, 'Руководитель']], default=1, verbose_name='Роль пользователя'),
        ),
    ]
