# Generated by Django 3.1.2 on 2020-10-31 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_auto_20201031_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Район'),
        ),
    ]
