# Generated by Django 3.1.2 on 2020-10-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название показателя')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Базовый показетель',
                'verbose_name_plural': 'Базоваые показетели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Критерии')),
                ('formula', models.CharField(max_length=200, verbose_name='Алгоритм расчета показетля')),
                ('indicators', models.ManyToManyField(to='base.BasicIndicators', verbose_name='Базоваые показетели')),
            ],
            options={
                'verbose_name': 'Критерии',
                'verbose_name_plural': 'Критерии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.city')),
                ('criteria', models.ManyToManyField(to='base.Criteria')),
            ],
            options={
                'verbose_name': 'Мниципальный район',
                'verbose_name_plural': 'Муниципальные районы',
                'ordering': ['city'],
            },
        ),
    ]
