# Generated by Django 3.1.2 on 2020-10-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Алгоритм расчета показетля'),
        ),
    ]
