# Generated by Django 3.1.2 on 2020-10-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201031_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['order', 'city'], 'verbose_name': 'Мниципальный район', 'verbose_name_plural': 'Муниципальные районы'},
        ),
        migrations.AddField(
            model_name='municipality',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
