# Generated by Django 3.1.2 on 2020-10-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201031_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='base.BasicIndicators', verbose_name='Базоваые показетели'),
        ),
    ]
