# Generated by Django 3.1.2 on 2020-10-31 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_city_description'),
        ('base', '0005_auto_20201031_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['order', 'city'], 'verbose_name': 'Муниципальный район', 'verbose_name_plural': 'Муниципальные районы'},
        ),
        migrations.AddField(
            model_name='criteria',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.city', verbose_name='Муниципальный район'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='criteria',
            field=models.ManyToManyField(to='base.Criteria', verbose_name='Критерии'),
        ),
    ]
