# Generated by Django 3.1.2 on 2020-11-01 00:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_criteria_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteria',
            options={'ordering': ['name'], 'verbose_name': 'Критерий/Индикатор', 'verbose_name_plural': 'Критерии/Индикатор'},
        ),
        migrations.AddField(
            model_name='municipality',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='api',
            field=models.CharField(blank=True, help_text='Настройки подключения к API из открытых источников', max_length=250, null=True, verbose_name='API URI'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='base.BasicIndicators', verbose_name='Базоваые показатели'),
        ),

    ]
