# Generated by Django 3.1.2 on 2020-11-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201101_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='index',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Index'),
        ),
    ]
