# Generated by Django 3.1.2 on 2020-11-01 02:41

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201101_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='criteria',
            field=models.ManyToManyField(related_name='municipality', to='base.Criteria', verbose_name='Критерии'),
        ),
        migrations.AlterField(
            model_name='municipalitycriteria',
            name='dataset',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
