# Generated by Django 3.1.2 on 2020-11-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20201101_0014'),
        ('base', '0009_auto_20201101_0241'),
    ]

    operations = [
    ]
