# Generated by Django 3.1.2 on 2020-11-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_merge_20201101_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='api_enable',
            field=models.BooleanField(default=False, verbose_name='Включить API'),
        ),
        migrations.AddField(
            model_name='municipalitycriteria',
            name='dataset_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Index'),
        ),
    ]
